language: node_js
node_js: 4
script:
  - npm install
  - npm run build
  - git describe
deploy:
  provider: releases
  api_key:
    secure:
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    repo: fortinet/autoscale
    tags: true
    all_branches: true
