language: node_js
node_js: 8.11.1
script:
  - npm install
  - npm run build
  - npm run unzip-aws-artifacts
  # - git describe
before_deploy:
  - pip install --user --upgrade awscli
deploy:
  - provider: script
    script: ~/.local/bin/aws s3 sync distAWS s3://fortinet-github-aws-release-artifacts/fortigate-autoscale/$TRAVIS_BRANCH --region=us-west-2 --delete
    skip_cleanup: true
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH != dependabot"
  # - provider: releases
  #   api_key:
  #     secure: q4IV9e8MzRe8R3hLT8gpJRCJqtiGmP06mu12MPqtr2VFzDcGjD/OB8ZaA2yh5pOpZDXU3Cifo34Cytz5lVH4bax4r6aGhQ2e5zcC8DZ1GgDZbvttqasVm8GB8x5haVmo9Ai8KcPsNpfcWZLubpi1A04GqqHSvH6nG6brvbTOmMGbvx6fBcs99XNaW/YgUkJAaBPdtv5rEOpMSxkH8DcYivCyTnJ+uxpA2RHFssFJu6DKhx7+zk/fVZbZ92ro7PCgtuZ6SNs6wEMQxlFG6PEZTv93s6yxks2CfqdapX77RGgF8+5yySwzYNSLGkxwSc1URjhp/kUWCe+P6VfPGNB3+yuM/9JtCpXlD5XKxQfgA+KP5MOwgydiFv/zZe9kdN56LlAfb6sjyuw3RONYjVNTZSiurPabnh0yH4VvJ4LaBX/Chhua5z8hX1oBz4a9hmMoAAXf/LQ7P3zTccaWoa1+S2m9VXLAGMLL8pEYi8nGM4R56IDvzsO6JMBjzHeI5tDpmfjCI1ZHsiyLyVplNmcq99qVT12AQbStqSjgy8WdpF0Ug5iyafeH23OhLRD+S1AI4zYFREOYtk/h0CR5MGgk0M4VyN2uMPW4j/WtSaC1tx2ejhoOBb4jN0V8TLXVGVfmO4Qhdop7gEvI3VEvaIBTKP1jVFZOjfnp5V5k8KNTuYo=
  #   file_glob: true
  #   file: dist/*
  #   skip_cleanup: true
  #   on:
  #     repo: fortinet/fortigate-autoscale
  #     tags: true
  #     branch: master
  # - provider: s3
  #   access_key_id:
  #     secure: HZkltwvNh6stD0vXtgd1OAAqMo36JkXKt/jXhA58cTduNJQg8IzpBCBp8o+MADHVcAhqIBGstzUHdqY4Oh3tCNDtpugjrulxqxdxnwhW511Um6D9OuCPveAsf5IlxBmIP7yzp9UMTDqUm2mMhuPm9pJYio352+uzaMuB+YrjyRTm4KxldRqWZyyvpspVPucmf4Txa7U1gP4PXMNNyu2pJ/aZMsKSOQk89jEOaUMyuK9mUhbg21j5nDOknoY5txWkUG0FiXuJ52BdqCzTgMRwFgHcjJ/GwDFY7SknRc1Zi9QcAm0yK0WCTsqo3Vupyb1is3rYV4mNSVghk04uBLLtFpKbFPwA8tCa/g1e3UeJR79uK8EFvzDiIbtgItyLi7mkXSTs1FZNZ6J2g4LvgQkRQ2WgO1ejTyyxnnGvyGOYcuQLw3bNO63WSN+Jj7BNLdepcQ0VQd4gN5IBwT8OJXtuEnARPfua7Wf7s5ZWsVWuy5YmfN7COnFektIDBUz5MgvIPHfYkRuRbr4WLzlwk6Wdr0lMjFQvvGRcB1LF5rJ4wyxqtHWFZrzc3HY4DNuoZCOPaEOB7zmNJlU9mwkfvvD8bYbaNOYnGKEyACwkaH5D7R8df5A75z+CjAlK1dCCRmw9cPnq+izhebCqXq3z+gGxuswkIvbso5OaNBedACF4O48=
  #   secret_access_key:
  #     secure: vdkha+cm03luG2BPi3kNzzyctIObZEazbrM2lukcESaiaN5Yi8YBA6p6EZayOM+8yAzi3xSpOn/rtxiDK/4BUwqcfSPbOr4Esj/44tiXLPvQSH3a6VC4ad8ZtzBJbMIB4C0PxQE9hU73i6TXkefAdj9MYlgM44qVhZAj9RJ8KJVM+du27Cchsj4Feb9vGO7bIdFJV4E09VjUEINNZBsvc1ZvSlMLIEqPknOKCRkx539pFH3i1J9zwzSKdDvz5/ccsXOHQ36+FDQuY4r3Y0yunHysTWCPyxqKJ412tYpmEzHLS8x+vRHBMyub8fb/dSvXCYXfSsy6ewpa23y4LywW3Y7nZSTCfMV0f3YTtwQ+I1OPis6vXXlOYKWmsVV4Jp0O7EoW72B0fmB86BXOO9weaKf0GiDfyP4UvGmZkP91xcSJiQw68jKlim7CV0hbjsTAIBesARo5wUkUtjJMKMmffm4EJvtmd0loxJDznpqSWrsEhgg0XD2Zw4CLm+MGWLpfS7sDEgEE6BmUnQOJZFoCaE9JR1V8yNjaLh/sf1EXrHDPXMEmSsp6KE6usVHZwRHdCA4MlyuGSPErS2xNvxYHcb6KURRfrIlmqgE7hQJa2b7wlMYmmDqQA6170Yem6GIyK+tyqaWAj/JqUUo6z8N5FwN5NWngH0H4PsDxtsku9Wg=
  #   region: us-west-2
  #   bucket: fortinet-github-aws-release-artifacts
  #   acl: public_read
  #   skip_cleanup: true
  #   local_dir: distAWS
  #   upload-dir: fortigate-autoscale/$TRAVIS_BRANCH
  #   on:
  #     all_branches: true
env:
  global:
    - secure: "CUF96I/0cJwrJoT0MRMqBR6owpPszvxWY/Xr3SUP6sSlO919W3mKDEcsvCSaPxtOBTHZzjHPHXJEBGY47vp9uEMbXbKEWN4N1MFF8PqRYs83XEOH+3bNyNHGuxK3l7nTsn4r/rmEKDwXiMzDe5BEY3bniUCNeZUhK94Mp9cKt+jBNMdWIJUYK4YdMyVHJ16a/yfzgzKiIYOEh/244Zl3n+34OqwBELB7SEjnFGhKQDNgBa5ywnUrp+PB6nXX5bBbv0JB8pXYClAYLj+luL2IC3MgaJmi6wZjrsASWuoe9ml3UIkKuyYUxon6HbEliCUm06QgWa/jqAp4MIc9kyMQc9eRtcUCaDwkN2hIroKJa9/0mMJyvA20QeLpPji/ERjio5guUlrgR4fxcS4EJJY3MyIi1wrWRIlEYkHVpPrczkPgdTttob8xsaBjJnMZ5Cf3MZL3haY6RdZFVKGky3JMDO1OLGieGAmbm1ELEKhzhM0wNoG5O4ge1EVlJpBqKZ1/gfGu98GYnI7DjqdbjXVEKkrp0ziv5Ub7bk7wYJQ23ZhIuoO8QdxkSeDhEnjK2u1N82PbR7s3K7MPFSjdUz3pmfsPBm+i0RTmc4/M4JvdcWVqvk4hHR44TemhI765jhrlV6kSBmXKdh5nRx+VvzfZnrn9d2TIBWXMEeH1RHk3x0A="
    - secure: "xNE/o5jcMDEIm+GXYg1mDRfUnNjCwmTb+K/LqChKkY/KUD4HAjgx68Z6Qo1zM4yqT7oHeK8TUZTAM4MkYRClbrIZOyIFL+qbV231vSfYMz8DRsHxjuYLa98adWIPldjTT40MLgujPuERgb986oM3a5PKhufk3gCu4s9q9eYRJzKdMqDuBBMC3xbsObuFg6Mowm2Jj/6mI/rxrnD7gNXdjqrb8Ix7Wd1OP95lKitsJVSUAhMJyyC0j79/h5YaSnsocOwLINgYrDk+LVKvFcrX/BDvVLljRt4m8tfk2KYJNB4/YnpNGlret3bjLLnpLuSbvrJHB8xGwXedY7NiOvgW34O90v/6bBXYkUaLIiQ9BR1lAxmYMKJHpG/NaTqGiZDereCs3nt0goChp6jhq2yV6D0Nu1w+KDS7MOM6C3A5eTMZ0Xe+ShklETftilm9PMqPysCwyIhvxqTOSJXkI1R3BMh4fulPmR5anUoAyyxFCUrFQd0TMMZcbgsAgOa1ImTZjQYjulFC8J0lVOCSBUFCAmnYX3M42akSETwRgxR33hR14jj65TAQbTzL8KvUjg1VG8+wXknlf0e0RIHU4EsQmLDIzluJNbNamHsPXG+aEOGtXciXYVXi45dVGfGeKDgIOQ43OVmid2l/FjIuPOd9Xpk38JxJ7VeJ9hD7QEeEGV0="
